import type { SupabaseClient } from '@supabase/supabase-js';
import type { ChatStats, MessageRow, NewMessage, Profile } from '@/types/chat';
import { PAGE_SIZE, SEARCH_PAGE_SIZE } from './constants';

/** Messages as this person may see them: everything except what they deleted for themselves. */
const VISIBLE = 'messages_visible';

export const MESSAGE_COLUMNS =
  'id, sender_id, body, image_path, image_width, image_height, image_mime, image_size, audio_path, audio_duration_ms, audio_peaks, deleted_at, created_at';

/**
 * The newest PAGE_SIZE messages (or the PAGE_SIZE before `before`), oldest first.
 * `hasMore` tells the UI whether older messages exist.
 */
export async function fetchPage(
  supabase: SupabaseClient,
  before?: string,
): Promise<{ rows: MessageRow[]; hasMore: boolean }> {
  let query = supabase
    .from(VISIBLE)
    .select(MESSAGE_COLUMNS)
    .order('created_at', { ascending: false })
    .order('id', { ascending: false })
    .limit(PAGE_SIZE + 1);
  if (before) query = query.lt('created_at', before);

  const { data, error } = await query;
  if (error) throw error;

  const rows = (data ?? []) as unknown as MessageRow[];
  return { rows: rows.slice(0, PAGE_SIZE).reverse(), hasMore: rows.length > PAGE_SIZE };
}

/** Everything at or after `after`, oldest first. Used to fill gaps after a disconnect. */
export async function fetchAfter(supabase: SupabaseClient, after: string): Promise<MessageRow[]> {
  const collected: MessageRow[] = [];
  let cursor = after;

  for (let page = 0; page < 5; page++) {
    const { data, error } = await supabase
      .from(VISIBLE)
      .select(MESSAGE_COLUMNS)
      .gte('created_at', cursor)
      .order('created_at', { ascending: true })
      .order('id', { ascending: true })
      .limit(200);
    if (error) throw error;

    const rows = (data ?? []) as unknown as MessageRow[];
    collected.push(...rows);
    if (rows.length < 200) break;
    cursor = rows[rows.length - 1].created_at;
  }
  return collected;
}

export async function fetchProfiles(supabase: SupabaseClient): Promise<Profile[]> {
  const { data, error } = await supabase.from('profiles').select('id, username, display_name, preferences');
  if (error) throw error;
  return (data ?? []) as Profile[];
}

export async function fetchStats(supabase: SupabaseClient): Promise<ChatStats> {
  const { data, error } = await supabase.rpc('chat_stats');
  if (error) throw error;
  const row = Array.isArray(data) ? data[0] : data;
  return {
    total: Number(row?.total ?? 0),
    photos: Number(row?.photos ?? 0),
    firstAt: (row?.first_message_at as string | null | undefined) ?? null,
  };
}

/**
 * Inserts a message. Because the id is generated by the sender, retrying after an
 * unclear failure is safe: if the first attempt actually landed, we just read it back.
 */
export async function insertMessage(supabase: SupabaseClient, message: NewMessage): Promise<MessageRow> {
  const { data, error } = await supabase.from('messages').insert(message).select(MESSAGE_COLUMNS).single();

  if (!error) return data as unknown as MessageRow;

  if (error.code === '23505') {
    const existing = await supabase.from('messages').select(MESSAGE_COLUMNS).eq('id', message.id).single();
    if (!existing.error) return existing.data as unknown as MessageRow;
    throw existing.error;
  }
  throw error;
}

/** True if any message is older than `iso`. */
export async function hasOlderThan(supabase: SupabaseClient, iso: string): Promise<boolean> {
  const { data, error } = await supabase.from(VISIBLE).select('id').lt('created_at', iso).limit(1);
  if (error) throw error;
  return (data ?? []).length > 0;
}

/**
 * Messages from `from` (inclusive) up to `before` (exclusive), newest first, one batch at a time.
 * Used to load everything between an old search result and the messages already on screen.
 */
export async function fetchBefore(supabase: SupabaseClient, before: string, from: string, limit = 500): Promise<MessageRow[]> {
  const { data, error } = await supabase
    .from(VISIBLE)
    .select(MESSAGE_COLUMNS)
    .lt('created_at', before)
    .gte('created_at', from)
    .order('created_at', { ascending: false })
    .order('id', { ascending: false })
    .limit(limit);
  if (error) throw error;
  return (data ?? []) as unknown as MessageRow[];
}

/** Text search across the whole conversation, newest matches first. */
export async function searchMessages(
  supabase: SupabaseClient,
  term: string,
  before?: string,
): Promise<{ rows: MessageRow[]; hasMore: boolean }> {
  // Treat the search as plain text: neutralise LIKE wildcards.
  const escaped = term.replace(/[\\%_]/g, (c) => `\\${c}`);
  let query = supabase
    .from(VISIBLE)
    .select(MESSAGE_COLUMNS)
    .not('body', 'is', null)
    .ilike('body', `%${escaped}%`)
    .order('created_at', { ascending: false })
    .order('id', { ascending: false })
    .limit(SEARCH_PAGE_SIZE + 1);
  if (before) query = query.lt('created_at', before);

  const { data, error } = await query;
  if (error) throw error;
  const rows = (data ?? []) as unknown as MessageRow[];
  return { rows: rows.slice(0, SEARCH_PAGE_SIZE), hasMore: rows.length > SEARCH_PAGE_SIZE };
}

/** Saves this person's appearance. Only their own row can be changed (enforced by the database). */
export async function savePreferences(supabase: SupabaseClient, userId: string, preferences: object): Promise<void> {
  const { error } = await supabase.from('profiles').update({ preferences }).eq('id', userId);
  if (error) throw error;
}

/** Messages unsent since `sinceIso` (used to catch up on unsends missed while offline). */
export async function fetchUnsentSince(supabase: SupabaseClient, sinceIso: string): Promise<MessageRow[]> {
  const { data, error } = await supabase
    .from(VISIBLE)
    .select(MESSAGE_COLUMNS)
    .not('deleted_at', 'is', null)
    .gte('deleted_at', sinceIso)
    .limit(200);
  if (error) throw error;
  return (data ?? []) as unknown as MessageRow[];
}

/** Unsend for everyone. Only the sender can; the database enforces it. Returns the files that were attached. */
export async function unsendMessage(
  supabase: SupabaseClient,
  id: string,
): Promise<{ image: string | null; audio: string | null }> {
  const { data, error } = await supabase.rpc('unsend_message', { p_id: id });
  if (error) throw error;
  const row = Array.isArray(data) ? data[0] : data;
  return { image: row?.removed_image ?? null, audio: row?.removed_audio ?? null };
}

/** Delete for me. The other person still sees the message. Doing it twice is fine. */
export async function hideMessage(supabase: SupabaseClient, userId: string, messageId: string): Promise<void> {
  const { error } = await supabase.from('message_hides').insert({ user_id: userId, message_id: messageId });
  if (error && error.code !== '23505') throw error;
}

/** Best-effort removal of the files of an unsent message. A leftover file is harmless, so failures are ignored. */
export async function removeFiles(supabase: SupabaseClient, bucket: string, paths: Array<string | null>): Promise<void> {
  const list = paths.filter((p): p is string => Boolean(p));
  if (list.length === 0) return;
  try {
    await supabase.storage.from(bucket).remove(list);
  } catch {
    /* ignore */
  }
}
