import type { SupabaseClient } from '@supabase/supabase-js';
import type { ChatStats, MessageRow, NewMessage, Profile } from '@/types/chat';
import { PAGE_SIZE } from './constants';

export const MESSAGE_COLUMNS =
  'id, sender_id, body, image_path, image_width, image_height, image_mime, image_size, created_at';

/**
 * The newest PAGE_SIZE messages (or the PAGE_SIZE before `before`), oldest first.
 * `hasMore` tells the UI whether older messages exist.
 */
export async function fetchPage(
  supabase: SupabaseClient,
  before?: string,
): Promise<{ rows: MessageRow[]; hasMore: boolean }> {
  let query = supabase
    .from('messages')
    .select(MESSAGE_COLUMNS)
    .order('created_at', { ascending: false })
    .order('id', { ascending: false })
    .limit(PAGE_SIZE + 1);
  if (before) query = query.lt('created_at', before);

  const { data, error } = await query;
  if (error) throw error;

  const rows = (data ?? []) as unknown as MessageRow[];
  return { rows: rows.slice(0, PAGE_SIZE).reverse(), hasMore: rows.length > PAGE_SIZE };
}

/** Everything at or after `after`, oldest first. Used to fill gaps after a disconnect. */
export async function fetchAfter(supabase: SupabaseClient, after: string): Promise<MessageRow[]> {
  const collected: MessageRow[] = [];
  let cursor = after;

  for (let page = 0; page < 5; page++) {
    const { data, error } = await supabase
      .from('messages')
      .select(MESSAGE_COLUMNS)
      .gte('created_at', cursor)
      .order('created_at', { ascending: true })
      .order('id', { ascending: true })
      .limit(200);
    if (error) throw error;

    const rows = (data ?? []) as unknown as MessageRow[];
    collected.push(...rows);
    if (rows.length < 200) break;
    cursor = rows[rows.length - 1].created_at;
  }
  return collected;
}

export async function fetchProfiles(supabase: SupabaseClient): Promise<Profile[]> {
  const { data, error } = await supabase.from('profiles').select('id, username, display_name');
  if (error) throw error;
  return (data ?? []) as Profile[];
}

export async function fetchStats(supabase: SupabaseClient): Promise<ChatStats> {
  const { data, error } = await supabase.rpc('chat_stats');
  if (error) throw error;
  const row = Array.isArray(data) ? data[0] : data;
  return {
    total: Number(row?.total ?? 0),
    photos: Number(row?.photos ?? 0),
    firstAt: (row?.first_message_at as string | null | undefined) ?? null,
  };
}

/**
 * Inserts a message. Because the id is generated by the sender, retrying after an
 * unclear failure is safe: if the first attempt actually landed, we just read it back.
 */
export async function insertMessage(supabase: SupabaseClient, message: NewMessage): Promise<MessageRow> {
  const { data, error } = await supabase.from('messages').insert(message).select(MESSAGE_COLUMNS).single();

  if (!error) return data as unknown as MessageRow;

  if (error.code === '23505') {
    const existing = await supabase.from('messages').select(MESSAGE_COLUMNS).eq('id', message.id).single();
    if (!existing.error) return existing.data as unknown as MessageRow;
    throw existing.error;
  }
  throw error;
}
